---
title: "Valence experiments"
output: html_notebook
---


```{r}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(dplyr)
library(tidyr)
library(langcog)
library(ggplot2)
library(ggthemes)
library(forcats)
library(knitr)
theme_set(theme_few())

data.path <- "../data/pilots/"

readData <- function(project){
  return(read.csv(paste(data.path, project, "/", project, "-trials.csv", sep = "")))
}

readSubjectInfo <- function(project){
  return(read.csv(paste(data.path, project, "/", project, "-subject_information.csv", sep = "")))
}
```

### Overview of Experiments:


1. Valence 1 (5/2/2016): Participants rate on a scale from "very bad" to "very good" how good it is to have the underlined property.


### Subject information


Did people enjoy the experiment?

```{r}
df.info <- readSubjectInfo("pilot-valence-1")
table(df.info$enjoyment)
```
Comments?

```{r}
df.info %>% select(comments) %>% filter(comments != "") %>% kable()
```



```{r}
df.val <- readData("pilot-valence-1")  %>%
  mutate(verb.phrase = gsub("&quotechar", "", verb.phrase),
         entire.sentence = gsub("&quotechar", "", entire.sentence))
```

```{r}
df.val.summary <- df.val %>%
  group_by(entire.sentence, verb.phrase) %>%
  multi_boot_standard(column = "valence")
```

```{r fig.width=8}
df.val.summary <- df.val.summary %>%
  ungroup() %>%
  mutate(verb.phrase = 
           factor(verb.phrase, levels = verb.phrase[order(mean)]))


ggplot(df.val.summary, aes(x = verb.phrase, 
                           y = mean, ymin = ci_lower, ymax = ci_upper))+
  geom_bar(stat = 'identity', position = position_dodge())+
  geom_errorbar(position = position_dodge())+
  coord_flip()+
  ylab("Valence (1 = good; 0 = bad)")+
  ylim(0,1)+
  geom_hline(yintercept = 0.5, lty = 3)
```


Full distributions

```{r fig.width=12}
df.val %>%
  ggplot(., aes( x = valence))+
  geom_histogram()+
  facet_wrap(~verb.phrase)
```

